#!/usr/bin/env node
// Derives dist/tokens.css + dist/RebelleTokens.swift from the committed Claude
// Design export in ds/. The export is the source of truth — regenerate after
// every re-import, never hand-edit outputs.

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokensDir = join(root, 'ds', 'tokens');
const distDir = join(root, 'dist');
mkdirSync(distDir, { recursive: true });

const ORDER = ['colors', 'typography', 'spacing', 'borders', 'motion', 'fonts'];
const files = readdirSync(tokensDir).filter((f) => f.endsWith('.css'));
const ordered = [
  ...ORDER.map((n) => `${n}.css`).filter((f) => files.includes(f)),
  ...files.filter((f) => !ORDER.includes(f.replace('.css', ''))).sort(),
];

const header = `/* GENERATED by @rebelle/core scripts/build-tokens.mjs — do not edit.
 * Source: ds/ (Claude Design export, project 4a29d0b6-616d-4dab-81e1-e7917a18c636).
 * Re-import the design system, replace ds/, then run: pnpm build:tokens
 */\n\n`;

const css = ordered.map((f) => readFileSync(join(tokensDir, f), 'utf8')).join('\n');
writeFileSync(join(distDir, 'tokens.css'), header + css);

// --- Swift color output (colors.css only) ---------------------------------
const colorsCss = readFileSync(join(tokensDir, 'colors.css'), 'utf8');
const entries = [];
const re = /--([a-z0-9-]+):\s*(#[0-9a-fA-F]{3,8}|rgba?\([^)]+\))\s*;/g;
let m;
while ((m = re.exec(colorsCss)) !== null) {
  const name = m[1].replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
  const rgba = parseColor(m[2]);
  if (rgba) entries.push({ name, rgba });
}

function parseColor(value) {
  if (value.startsWith('#')) {
    let hex = value.slice(1);
    if (hex.length === 3) hex = [...hex].map((c) => c + c).join('');
    if (hex.length === 6) hex += 'ff';
    if (hex.length !== 8) return null;
    const n = parseInt(hex, 16);
    return [(n >>> 24) & 255, (n >>> 16) & 255, (n >>> 8) & 255, (n & 255) / 255];
  }
  const parts = value.match(/rgba?\(([^)]+)\)/)?.[1].split(',').map((s) => parseFloat(s.trim()));
  if (!parts || parts.length < 3) return null;
  return [parts[0], parts[1], parts[2], parts.length === 4 ? parts[3] : 1];
}

const swiftLines = entries.map(({ name, rgba: [r, g, b, a] }) => {
  const f = (v) => (v / 255).toFixed(4);
  return `    public static let ${name} = Color(red: ${f(r)}, green: ${f(g)}, blue: ${f(b)}, opacity: ${a.toFixed(4)})`;
});

const swift = `// GENERATED by @rebelle/core scripts/build-tokens.mjs — do not edit.
// Source: ds/tokens/colors.css (Claude Design export 4a29d0b6-616d-4dab-81e1-e7917a18c636).

import SwiftUI

public enum RebelleTokens {
${swiftLines.join('\n')}
}
`;
writeFileSync(join(distDir, 'RebelleTokens.swift'), swift);

console.log(`tokens.css: ${ordered.length} source files · RebelleTokens.swift: ${entries.length} colors`);
