#!/usr/bin/env node
// Derives dist/tokens.css, dist/system.css and dist/RebelleTokens.swift from
// the committed Claude Design export in ds/. The export is the source of truth
// — regenerate after every re-import, never hand-edit outputs.
//
// Two CSS outputs because the Field Glass system splits its language in two:
//   tokens.css — ds/tokens/ only: what is BRAND-WIDE (fonts, color, type,
//                space, radii, motion). Safe for any consumer, no classes.
//   system.css — tokens plus each ground's own language (Navy, Photo, Field
//                Glass, Terrain, Roadbook, On-Air), the component register and
//                the document laws. This is what a web surface imports.

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PROJECT = 'b992548a-8479-40e9-bbce-4bd98128a675'; // Claude Design — Rebelle Rally · Field Glass

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dsDir = join(root, 'ds');
const tokensDir = join(dsDir, 'tokens');
const distDir = join(root, 'dist');
mkdirSync(distDir, { recursive: true });

const ORDER = ['colors', 'typography', 'spacing', 'radii', 'motion', 'fonts'];
const files = readdirSync(tokensDir).filter((f) => f.endsWith('.css'));
const ordered = [
  ...ORDER.map((n) => `${n}.css`).filter((f) => files.includes(f)),
  ...files.filter((f) => !ORDER.includes(f.replace('.css', ''))).sort(),
];

// The grounds, in ds/styles.css order, then the shared registers.
const SYSTEM_FILES = [
  '02-navy-ground/navy.css',
  '03-photo-ground/photo.css',
  '04-field-glass/field-glass.css',
  '05-terrain-paper/terrain.css',
  '06-roadbook-paper/roadbook.css',
  '07-broadcast-on-air/on-air.css',
  '08-components/components.css',
  '17-documents/document.css',
];

const header = (what) => `/* GENERATED by @rebelle/core scripts/build-tokens.mjs — do not edit.
 * Source: ds/ (Claude Design export, project ${PROJECT}).
 * ${what}
 * Re-import the design system, replace ds/, then run: pnpm build:tokens
 */\n\n`;

// Licensed faces never reach a generated stylesheet: Tungsten is broadcast /
// internal tooling only ("the web uses Oswald" — ds/tokens/fonts.css), and the
// .otf files themselves are deliberately NOT in ds/. Stripping the @font-face
// here (rather than editing ds/) keeps ds/ a faithful import while the dist a
// consumer bundles stays clean of dangling, unlicensed references.
function stripLocalFontFaces(css) {
  return css.replace(/@font-face\s*\{[^}]*\}/g, (block) =>
    block.includes('../assets/fonts/') ? '' : block,
  );
}

// Ground CSS references its assets as '../assets/…' (relative to the ground's
// own folder inside ds/). dist/ sits beside ds/, so from dist/system.css the
// same files live at '../ds/assets/…'. Rewritten here so a bundler resolves
// them; the files ship in ds/assets/.
function rewriteAssetUrls(css) {
  return css.replace(/url\((['"]?)\.\.\/assets\//g, 'url($1../ds/assets/');
}

// --- CSS outputs ----------------------------------------------------------
// @import must precede every other rule, and the ds/ file carrying the webfont
// import is not necessarily first in ORDER. Hoist imports out of the
// concatenation rather than relying on file order: browsers drop a late
// @import silently, so a re-import that reshuffles ds/ would kill the webfonts
// with no error anywhere but a build warning.
function emit(name, sources, what) {
  const concatenated = sources.map((f) => readFileSync(join(dsDir, f), 'utf8')).join('\n');
  const { imports, body } = hoistImports(stripLocalFontFaces(concatenated));
  const importBlock = imports.length
    ? `/* Hoisted from ds/ — @import must precede all other rules. */\n${imports.join('\n')}\n\n`
    : '';
  writeFileSync(join(distDir, name), header(what) + importBlock + rewriteAssetUrls(body));
  return imports.length;
}

const tokenSources = ordered.map((f) => `tokens/${f}`);
const hoistedTokens = emit('tokens.css', tokenSources, 'tokens.css — brand-wide tokens only.');
emit(
  'system.css',
  [...tokenSources, ...SYSTEM_FILES],
  'system.css — tokens + the six grounds + the component register + document laws.',
);

function hoistImports(css) {
  // Blank out comment bodies first, preserving length so offsets still line up
  // with the real source. Keeps an "@import" named in one of ds/'s doc banners
  // from being hoisted as if it were a statement.
  const masked = css.replace(/\/\*[\s\S]*?\*\//g, (c) => c.replace(/[^\n]/g, ' '));
  const re = /@import\b/g;
  const imports = [];
  let body = '';
  let cursor = 0;
  let m;
  while ((m = re.exec(masked)) !== null) {
    let end = endOfStatement(masked, m.index);
    if (end < 0) continue; // unterminated — not ours to repair, leave it in place
    while (/[ \t]/.test(masked[end])) end++;
    if (masked[end] === '\n') end++;
    const statement = css.slice(m.index, end).trim();
    if (!imports.includes(statement)) imports.push(statement);
    body += css.slice(cursor, m.index);
    cursor = end;
    re.lastIndex = end;
  }
  return { imports, body: body + css.slice(cursor) };
}

// Offset just past the `;` closing the statement at `start`. Semicolons inside
// strings and parens don't count — Google Fonts URLs are full of them
// (`wght@400;500;600;700`).
function endOfStatement(css, start) {
  let quote = null;
  let depth = 0;
  for (let i = start; i < css.length; i++) {
    const ch = css[i];
    if (quote) {
      if (ch === '\\') i++;
      else if (ch === quote) quote = null;
    } else if (ch === '"' || ch === "'") quote = ch;
    else if (ch === '(') depth++;
    else if (ch === ')') depth--;
    else if (ch === ';' && depth === 0) return i + 1;
  }
  return -1;
}

// --- Swift color output (colors.css only) ---------------------------------
const colorsCss = readFileSync(join(tokensDir, 'colors.css'), 'utf8');
const entries = [];
const re = /--([a-z0-9-]+):\s*(#[0-9a-fA-F]{3,8}|rgba?\([^)]+\))\s*;/g;
let m;
while ((m = re.exec(colorsCss)) !== null) {
  const name = m[1].replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
  const rgba = parseColor(m[2]);
  if (rgba) entries.push({ name, rgba });
}

function parseColor(value) {
  if (value.startsWith('#')) {
    let hex = value.slice(1);
    if (hex.length === 3) hex = [...hex].map((c) => c + c).join('');
    if (hex.length === 6) hex += 'ff';
    if (hex.length !== 8) return null;
    const n = parseInt(hex, 16);
    return [(n >>> 24) & 255, (n >>> 16) & 255, (n >>> 8) & 255, (n & 255) / 255];
  }
  const parts = value.match(/rgba?\(([^)]+)\)/)?.[1].split(',').map((s) => parseFloat(s.trim()));
  if (!parts || parts.length < 3) return null;
  return [parts[0], parts[1], parts[2], parts.length === 4 ? parts[3] : 1];
}

const swiftLines = entries.map(({ name, rgba: [r, g, b, a] }) => {
  const f = (v) => (v / 255).toFixed(4);
  return `    public static let ${name} = Color(red: ${f(r)}, green: ${f(g)}, blue: ${f(b)}, opacity: ${a.toFixed(4)})`;
});

const swift = `// GENERATED by @rebelle/core scripts/build-tokens.mjs — do not edit.
// Source: ds/tokens/colors.css (Claude Design export ${PROJECT}).

import SwiftUI

public enum RebelleTokens {
${swiftLines.join('\n')}
}
`;
writeFileSync(join(distDir, 'RebelleTokens.swift'), swift);

console.log(
  `tokens.css: ${ordered.length} source files, ${hoistedTokens} @import hoisted · system.css: +${SYSTEM_FILES.length} ground/register files · RebelleTokens.swift: ${entries.length} colors`,
);
