#!/usr/bin/env node
// Derives dist/tokens.css + dist/RebelleTokens.swift from the committed Claude
// Design export in ds/. The export is the source of truth — regenerate after
// every re-import, never hand-edit outputs.

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokensDir = join(root, 'ds', 'tokens');
const distDir = join(root, 'dist');
mkdirSync(distDir, { recursive: true });

const ORDER = ['colors', 'typography', 'spacing', 'borders', 'motion', 'fonts'];
const files = readdirSync(tokensDir).filter((f) => f.endsWith('.css'));
const ordered = [
  ...ORDER.map((n) => `${n}.css`).filter((f) => files.includes(f)),
  ...files.filter((f) => !ORDER.includes(f.replace('.css', ''))).sort(),
];

const header = `/* GENERATED by @rebelle/core scripts/build-tokens.mjs — do not edit.
 * Source: ds/ (Claude Design export, project 4a29d0b6-616d-4dab-81e1-e7917a18c636).
 * Re-import the design system, replace ds/, then run: pnpm build:tokens
 */\n\n`;

// --- CSS output -----------------------------------------------------------
// @import must precede every other rule, and the ds/ file carrying the webfont
// import is not necessarily first in ORDER. Hoist imports out of the
// concatenation rather than relying on file order: browsers drop a late
// @import silently, so a re-import that reshuffles ds/ would kill the webfonts
// with no error anywhere but a build warning.
const concatenated = ordered.map((f) => readFileSync(join(tokensDir, f), 'utf8')).join('\n');
const { imports, body } = hoistImports(concatenated);
const importBlock = imports.length
  ? `/* Hoisted from ds/tokens/ — @import must precede all other rules. */\n${imports.join('\n')}\n\n`
  : '';
writeFileSync(join(distDir, 'tokens.css'), header + importBlock + body);

function hoistImports(css) {
  // Blank out comment bodies first, preserving length so offsets still line up
  // with the real source. Keeps an "@import" named in one of ds/'s doc banners
  // from being hoisted as if it were a statement.
  const masked = css.replace(/\/\*[\s\S]*?\*\//g, (c) => c.replace(/[^\n]/g, ' '));
  const re = /@import\b/g;
  const imports = [];
  let body = '';
  let cursor = 0;
  let m;
  while ((m = re.exec(masked)) !== null) {
    let end = endOfStatement(masked, m.index);
    if (end < 0) continue; // unterminated — not ours to repair, leave it in place
    while (/[ \t]/.test(masked[end])) end++;
    if (masked[end] === '\n') end++;
    const statement = css.slice(m.index, end).trim();
    if (!imports.includes(statement)) imports.push(statement);
    body += css.slice(cursor, m.index);
    cursor = end;
    re.lastIndex = end;
  }
  return { imports, body: body + css.slice(cursor) };
}

// Offset just past the `;` closing the statement at `start`. Semicolons inside
// strings and parens don't count — Google Fonts URLs are full of them
// (`wght@400;500;600;700`).
function endOfStatement(css, start) {
  let quote = null;
  let depth = 0;
  for (let i = start; i < css.length; i++) {
    const ch = css[i];
    if (quote) {
      if (ch === '\\') i++;
      else if (ch === quote) quote = null;
    } else if (ch === '"' || ch === "'") quote = ch;
    else if (ch === '(') depth++;
    else if (ch === ')') depth--;
    else if (ch === ';' && depth === 0) return i + 1;
  }
  return -1;
}

// --- Swift color output (colors.css only) ---------------------------------
const colorsCss = readFileSync(join(tokensDir, 'colors.css'), 'utf8');
const entries = [];
const re = /--([a-z0-9-]+):\s*(#[0-9a-fA-F]{3,8}|rgba?\([^)]+\))\s*;/g;
let m;
while ((m = re.exec(colorsCss)) !== null) {
  const name = m[1].replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
  const rgba = parseColor(m[2]);
  if (rgba) entries.push({ name, rgba });
}

function parseColor(value) {
  if (value.startsWith('#')) {
    let hex = value.slice(1);
    if (hex.length === 3) hex = [...hex].map((c) => c + c).join('');
    if (hex.length === 6) hex += 'ff';
    if (hex.length !== 8) return null;
    const n = parseInt(hex, 16);
    return [(n >>> 24) & 255, (n >>> 16) & 255, (n >>> 8) & 255, (n & 255) / 255];
  }
  const parts = value.match(/rgba?\(([^)]+)\)/)?.[1].split(',').map((s) => parseFloat(s.trim()));
  if (!parts || parts.length < 3) return null;
  return [parts[0], parts[1], parts[2], parts.length === 4 ? parts[3] : 1];
}

const swiftLines = entries.map(({ name, rgba: [r, g, b, a] }) => {
  const f = (v) => (v / 255).toFixed(4);
  return `    public static let ${name} = Color(red: ${f(r)}, green: ${f(g)}, blue: ${f(b)}, opacity: ${a.toFixed(4)})`;
});

const swift = `// GENERATED by @rebelle/core scripts/build-tokens.mjs — do not edit.
// Source: ds/tokens/colors.css (Claude Design export 4a29d0b6-616d-4dab-81e1-e7917a18c636).

import SwiftUI

public enum RebelleTokens {
${swiftLines.join('\n')}
}
`;
writeFileSync(join(distDir, 'RebelleTokens.swift'), swift);

console.log(
  `tokens.css: ${ordered.length} source files, ${imports.length} @import hoisted · RebelleTokens.swift: ${entries.length} colors`,
);
