// Writes src/ui/land.ts: the world's land as one SVG path on the story map's
// grid (x = longitude + 180, y = 90 − latitude), for the Map part's still.
// Source: Natural Earth 1:110m land, public domain —
// https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson
//
//   node scripts/build-land.mjs <path to ne_110m_land.geojson>
import { readFileSync, writeFileSync } from 'node:fs';

const TOLERANCE = 0.35; // degrees a simplified edge may stray
const SMALLEST = 4; // square degrees; smaller islands are left out

const source = process.argv[2];
if (!source) throw new Error('give the path to ne_110m_land.geojson');
const { features } = JSON.parse(readFileSync(source, 'utf8'));

const project = ([longitude, latitude]) => [longitude + 180, 90 - latitude];

function area(ring) {
  let sum = 0;
  for (let i = 0; i < ring.length - 1; i += 1) sum += ring[i][0] * ring[i + 1][1] - ring[i + 1][0] * ring[i][1];
  return Math.abs(sum) / 2;
}

function distance([x, y], [x1, y1], [x2, y2]) {
  const dx = x2 - x1;
  const dy = y2 - y1;
  const length = Math.hypot(dx, dy);
  return length === 0 ? Math.hypot(x - x1, y - y1) : Math.abs(dy * x - dx * y + x2 * y1 - y2 * x1) / length;
}

// Douglas–Peucker, iterative so a long coastline cannot overflow the stack.
function simplify(points) {
  const keep = new Uint8Array(points.length);
  keep[0] = keep[points.length - 1] = 1;
  const stack = [[0, points.length - 1]];
  while (stack.length) {
    const [first, last] = stack.pop();
    let furthest = -1;
    let most = TOLERANCE;
    for (let i = first + 1; i < last; i += 1) {
      const d = distance(points[i], points[first], points[last]);
      if (d > most) { most = d; furthest = i; }
    }
    if (furthest !== -1) {
      keep[furthest] = 1;
      stack.push([first, furthest], [furthest, last]);
    }
  }
  return points.filter((_, i) => keep[i]);
}

const round = (value) => Math.round(value * 10) / 10;

const rings = features
  .flatMap((feature) => feature.geometry.coordinates)
  .map((ring) => ring.map(project))
  .filter((ring) => area(ring) >= SMALLEST)
  .map(simplify)
  .filter((ring) => ring.length >= 4);

// Relative moves, one decimal: the smallest honest path.
const path = rings.map((ring) => {
  let [x, y] = ring[0].map(round);
  const moves = [`M${x} ${y}`];
  for (const point of ring.slice(1, -1)) {
    const [nx, ny] = point.map(round);
    if (nx === x && ny === y) continue;
    moves.push(`${round(nx - x)} ${round(ny - y)}`);
    [x, y] = [nx, ny];
  }
  return `${moves[0]}l${moves.slice(1).join(' ')}z`;
}).join('');

writeFileSync(new URL('../src/ui/land.ts', import.meta.url), `// Generated by scripts/build-land.mjs from Natural Earth 1:110m land (public domain).
// The world's land on the story map's grid: x = longitude + 180, y = 90 − latitude.
export const LAND = '${path}';
`);
console.log(`${rings.length} shapes, ${path.length} characters`);
